name: NodeJS Github Action

on:
  push:
    branches: [main]

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use NodeJS 18
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Running test
              run: npm test
            - name: Sending Slack notifications on failure
              if: ${{ failure() }}
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: deploys
                SLACK_COLOR: "#9e2a2b"
                SLACK_ICON: https://cdn-icons-png.flaticon.com/512/427/427995.png?w=740&t=st=1686683003~exp=1686683603~hmac=8aad8cdfe4755475018c53a196d6f5d5480c3c8f8e23cbccaf3f23e7a5582eab
                SLACK_MESSAGE: "There was an error in the build😢"
                SLACK_TITLE: "Build status"
                SLACK_USERNAME: Slack Bot
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            - name: Sending Slack notifications on success
              if: ${{ success() }}
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: deploys
                SLACK_COLOR: "#00fc4c"
                SLACK_ICON: https://cdn-icons-png.flaticon.com/512/427/427995.png?w=740&t=st=1686683003~exp=1686683603~hmac=8aad8cdfe4755475018c53a196d6f5d5480c3c8f8e23cbccaf3f23e7a5582eab
                SLACK_MESSAGE: "Build successful👌"
                SLACK_TITLE: "Build status"
                SLACK_USERNAME: Slack Bot
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
    deploy:
        name: Deploying
        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to render
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                service-id: ${{secrets.RENDER_SERVICE_ID}}
                api-key: ${{secrets.RENDER_API_KEY}}

